/**
 * Curated emoji shortcode dictionary — the set you expect to work when typing
 * `:name:` in a chat composer. Aliases (e.g. `joy` + `rofl` pointing at the
 * same emoji, `thumbsup` + `+1` pointing at 👍) are fine — all keys appear in
 * the autocomplete list.
 */
export interface EmojiEntry {
  shortcode: string
  emoji: string
}

export const EMOJI_SHORTCODES: EmojiEntry[] = [
  // Faces — smiles
  { shortcode: 'grinning', emoji: '😀' },
  { shortcode: 'smiley', emoji: '😃' },
  { shortcode: 'smile', emoji: '😄' },
  { shortcode: 'grin', emoji: '😁' },
  { shortcode: 'laughing', emoji: '😆' },
  { shortcode: 'sweat_smile', emoji: '😅' },
  { shortcode: 'joy', emoji: '😂' },
  { shortcode: 'rofl', emoji: '🤣' },
  { shortcode: 'rolling_on_the_floor_laughing', emoji: '🤣' },
  { shortcode: 'slight_smile', emoji: '🙂' },
  { shortcode: 'upside_down', emoji: '🙃' },
  { shortcode: 'wink', emoji: '😉' },
  { shortcode: 'blush', emoji: '😊' },
  { shortcode: 'innocent', emoji: '😇' },
  { shortcode: 'heart_eyes', emoji: '😍' },
  { shortcode: 'smiling_face_with_hearts', emoji: '🥰' },
  { shortcode: 'kissing_heart', emoji: '😘' },
  { shortcode: 'kissing', emoji: '😗' },
  { shortcode: 'relaxed', emoji: '☺️' },
  { shortcode: 'yum', emoji: '😋' },
  { shortcode: 'stuck_out_tongue', emoji: '😛' },
  { shortcode: 'stuck_out_tongue_winking_eye', emoji: '😜' },
  { shortcode: 'zany', emoji: '🤪' },
  { shortcode: 'stuck_out_tongue_closed_eyes', emoji: '😝' },
  { shortcode: 'money_mouth', emoji: '🤑' },
  { shortcode: 'hugs', emoji: '🤗' },
  { shortcode: 'hand_over_mouth', emoji: '🤭' },
  { shortcode: 'shushing', emoji: '🤫' },
  { shortcode: 'thinking', emoji: '🤔' },
  { shortcode: 'zipper_mouth', emoji: '🤐' },
  { shortcode: 'raised_eyebrow', emoji: '🤨' },
  { shortcode: 'neutral', emoji: '😐' },
  { shortcode: 'expressionless', emoji: '😑' },
  { shortcode: 'no_mouth', emoji: '😶' },
  { shortcode: 'smirk', emoji: '😏' },
  { shortcode: 'unamused', emoji: '😒' },
  { shortcode: 'roll_eyes', emoji: '🙄' },
  { shortcode: 'grimacing', emoji: '😬' },
  { shortcode: 'lying', emoji: '🤥' },
  { shortcode: 'relieved', emoji: '😌' },
  { shortcode: 'pensive', emoji: '😔' },
  { shortcode: 'sleepy', emoji: '😪' },
  { shortcode: 'drooling', emoji: '🤤' },
  { shortcode: 'sleeping', emoji: '😴' },

  // Faces — negative / reactions
  { shortcode: 'mask', emoji: '😷' },
  { shortcode: 'face_with_thermometer', emoji: '🤒' },
  { shortcode: 'face_with_head_bandage', emoji: '🤕' },
  { shortcode: 'nauseated', emoji: '🤢' },
  { shortcode: 'vomiting', emoji: '🤮' },
  { shortcode: 'sneezing', emoji: '🤧' },
  { shortcode: 'hot', emoji: '🥵' },
  { shortcode: 'cold', emoji: '🥶' },
  { shortcode: 'woozy', emoji: '🥴' },
  { shortcode: 'dizzy_face', emoji: '😵' },
  { shortcode: 'exploding_head', emoji: '🤯' },
  { shortcode: 'cowboy', emoji: '🤠' },
  { shortcode: 'party', emoji: '🥳' },
  { shortcode: 'partying_face', emoji: '🥳' },
  { shortcode: 'disguised', emoji: '🥸' },
  { shortcode: 'sunglasses', emoji: '😎' },
  { shortcode: 'cool', emoji: '😎' },
  { shortcode: 'nerd', emoji: '🤓' },
  { shortcode: 'monocle', emoji: '🧐' },
  { shortcode: 'confused', emoji: '😕' },
  { shortcode: 'worried', emoji: '😟' },
  { shortcode: 'slight_frown', emoji: '🙁' },
  { shortcode: 'frowning2', emoji: '☹️' },
  { shortcode: 'open_mouth', emoji: '😮' },
  { shortcode: 'hushed', emoji: '😯' },
  { shortcode: 'astonished', emoji: '😲' },
  { shortcode: 'flushed', emoji: '😳' },
  { shortcode: 'pleading', emoji: '🥺' },
  { shortcode: 'frowning', emoji: '😦' },
  { shortcode: 'anguished', emoji: '😧' },
  { shortcode: 'fearful', emoji: '😨' },
  { shortcode: 'cold_sweat', emoji: '😰' },
  { shortcode: 'disappointed_relieved', emoji: '😥' },
  { shortcode: 'cry', emoji: '😢' },
  { shortcode: 'sob', emoji: '😭' },
  { shortcode: 'scream', emoji: '😱' },
  { shortcode: 'confounded', emoji: '😖' },
  { shortcode: 'persevere', emoji: '😣' },
  { shortcode: 'disappointed', emoji: '😞' },
  { shortcode: 'sweat', emoji: '😓' },
  { shortcode: 'weary', emoji: '😩' },
  { shortcode: 'tired_face', emoji: '😫' },
  { shortcode: 'yawning_face', emoji: '🥱' },
  { shortcode: 'triumph', emoji: '😤' },
  { shortcode: 'rage', emoji: '😡' },
  { shortcode: 'angry', emoji: '😠' },
  { shortcode: 'cursing', emoji: '🤬' },
  { shortcode: 'smiling_imp', emoji: '😈' },
  { shortcode: 'imp', emoji: '👿' },
  { shortcode: 'skull', emoji: '💀' },
  { shortcode: 'skull_and_crossbones', emoji: '☠️' },
  { shortcode: 'poop', emoji: '💩' },
  { shortcode: 'clown', emoji: '🤡' },
  { shortcode: 'ghost', emoji: '👻' },
  { shortcode: 'alien', emoji: '👽' },
  { shortcode: 'robot', emoji: '🤖' },

  // Cat faces
  { shortcode: 'smile_cat', emoji: '😺' },
  { shortcode: 'joy_cat', emoji: '😹' },
  { shortcode: 'smiley_cat', emoji: '😸' },
  { shortcode: 'heart_eyes_cat', emoji: '😻' },
  { shortcode: 'smirk_cat', emoji: '😼' },
  { shortcode: 'kissing_cat', emoji: '😽' },
  { shortcode: 'scream_cat', emoji: '🙀' },
  { shortcode: 'crying_cat_face', emoji: '😿' },
  { shortcode: 'pouting_cat', emoji: '😾' },

  // Hand gestures
  { shortcode: 'wave', emoji: '👋' },
  { shortcode: 'raised_back_of_hand', emoji: '🤚' },
  { shortcode: 'raised_hand', emoji: '✋' },
  { shortcode: 'vulcan', emoji: '🖖' },
  { shortcode: 'ok_hand', emoji: '👌' },
  { shortcode: 'pinched_fingers', emoji: '🤌' },
  { shortcode: 'pinching_hand', emoji: '🤏' },
  { shortcode: 'v', emoji: '✌️' },
  { shortcode: 'peace', emoji: '✌️' },
  { shortcode: 'crossed_fingers', emoji: '🤞' },
  { shortcode: 'love_you_gesture', emoji: '🤟' },
  { shortcode: 'metal', emoji: '🤘' },
  { shortcode: 'call_me', emoji: '🤙' },
  { shortcode: 'point_left', emoji: '👈' },
  { shortcode: 'point_right', emoji: '👉' },
  { shortcode: 'point_up_2', emoji: '👆' },
  { shortcode: 'middle_finger', emoji: '🖕' },
  { shortcode: 'point_down', emoji: '👇' },
  { shortcode: 'point_up', emoji: '☝️' },
  { shortcode: 'thumbsup', emoji: '👍' },
  { shortcode: '+1', emoji: '👍' },
  { shortcode: 'thumbsdown', emoji: '👎' },
  { shortcode: '-1', emoji: '👎' },
  { shortcode: 'fist', emoji: '✊' },
  { shortcode: 'punch', emoji: '👊' },
  { shortcode: 'left_facing_fist', emoji: '🤛' },
  { shortcode: 'right_facing_fist', emoji: '🤜' },
  { shortcode: 'clap', emoji: '👏' },
  { shortcode: 'raised_hands', emoji: '🙌' },
  { shortcode: 'open_hands', emoji: '👐' },
  { shortcode: 'palms_up', emoji: '🤲' },
  { shortcode: 'handshake', emoji: '🤝' },
  { shortcode: 'pray', emoji: '🙏' },
  { shortcode: 'muscle', emoji: '💪' },
  { shortcode: 'eyes', emoji: '👀' },
  { shortcode: 'brain', emoji: '🧠' },
  { shortcode: 'tongue', emoji: '👅' },

  // Hearts & symbols
  { shortcode: 'heart', emoji: '❤️' },
  { shortcode: 'orange_heart', emoji: '🧡' },
  { shortcode: 'yellow_heart', emoji: '💛' },
  { shortcode: 'green_heart', emoji: '💚' },
  { shortcode: 'blue_heart', emoji: '💙' },
  { shortcode: 'purple_heart', emoji: '💜' },
  { shortcode: 'black_heart', emoji: '🖤' },
  { shortcode: 'white_heart', emoji: '🤍' },
  { shortcode: 'brown_heart', emoji: '🤎' },
  { shortcode: 'broken_heart', emoji: '💔' },
  { shortcode: 'heart_on_fire', emoji: '❤️‍🔥' },
  { shortcode: 'two_hearts', emoji: '💕' },
  { shortcode: 'sparkling_heart', emoji: '💖' },
  { shortcode: 'revolving_hearts', emoji: '💞' },
  { shortcode: 'cupid', emoji: '💘' },
  { shortcode: 'gift_heart', emoji: '💝' },
  { shortcode: '100', emoji: '💯' },
  { shortcode: 'fire', emoji: '🔥' },
  { shortcode: 'star', emoji: '⭐' },
  { shortcode: 'sparkles', emoji: '✨' },
  { shortcode: 'boom', emoji: '💥' },
  { shortcode: 'zap', emoji: '⚡' },
  { shortcode: 'check', emoji: '✅' },
  { shortcode: 'white_check_mark', emoji: '✅' },
  { shortcode: 'x', emoji: '❌' },
  { shortcode: 'warning', emoji: '⚠️' },
  { shortcode: 'question', emoji: '❓' },
  { shortcode: 'exclamation', emoji: '❗' },

  // Food
  { shortcode: 'pizza', emoji: '🍕' },
  { shortcode: 'hamburger', emoji: '🍔' },
  { shortcode: 'fries', emoji: '🍟' },
  { shortcode: 'hotdog', emoji: '🌭' },
  { shortcode: 'taco', emoji: '🌮' },
  { shortcode: 'burrito', emoji: '🌯' },
  { shortcode: 'sushi', emoji: '🍣' },
  { shortcode: 'ramen', emoji: '🍜' },
  { shortcode: 'popcorn', emoji: '🍿' },
  { shortcode: 'cake', emoji: '🎂' },
  { shortcode: 'coffee', emoji: '☕' },
  { shortcode: 'beer', emoji: '🍺' },
  { shortcode: 'beers', emoji: '🍻' },
  { shortcode: 'wine_glass', emoji: '🍷' },
  { shortcode: 'cocktail', emoji: '🍸' },
  { shortcode: 'tropical_drink', emoji: '🍹' },
  { shortcode: 'apple', emoji: '🍎' },
  { shortcode: 'banana', emoji: '🍌' },

  // Objects / misc
  { shortcode: 'tada', emoji: '🎉' },
  { shortcode: 'party_popper', emoji: '🎉' },
  { shortcode: 'confetti_ball', emoji: '🎊' },
  { shortcode: 'balloon', emoji: '🎈' },
  { shortcode: 'gift', emoji: '🎁' },
  { shortcode: 'trophy', emoji: '🏆' },
  { shortcode: 'medal', emoji: '🏅' },
  { shortcode: 'rocket', emoji: '🚀' },
  { shortcode: 'computer', emoji: '💻' },
  { shortcode: 'keyboard', emoji: '⌨️' },
  { shortcode: 'phone', emoji: '📱' },
  { shortcode: 'bulb', emoji: '💡' },
  { shortcode: 'bell', emoji: '🔔' },
  { shortcode: 'lock', emoji: '🔒' },
  { shortcode: 'unlock', emoji: '🔓' },
  { shortcode: 'key', emoji: '🔑' },
  { shortcode: 'mag', emoji: '🔍' },
  { shortcode: 'link', emoji: '🔗' },
  { shortcode: 'hammer', emoji: '🔨' },
  { shortcode: 'wrench', emoji: '🔧' },
  { shortcode: 'gear', emoji: '⚙️' },
  { shortcode: 'bug', emoji: '🐛' },
  { shortcode: 'ok', emoji: '🆗' },
  { shortcode: 'new', emoji: '🆕' },
  { shortcode: 'up', emoji: '🆙' },
  { shortcode: 'cool2', emoji: '🆒' },
  { shortcode: 'free', emoji: '🆓' },

  // Animals
  { shortcode: 'dog', emoji: '🐶' },
  { shortcode: 'cat', emoji: '🐱' },
  { shortcode: 'mouse', emoji: '🐭' },
  { shortcode: 'hamster', emoji: '🐹' },
  { shortcode: 'rabbit', emoji: '🐰' },
  { shortcode: 'fox', emoji: '🦊' },
  { shortcode: 'bear', emoji: '🐻' },
  { shortcode: 'panda', emoji: '🐼' },
  { shortcode: 'koala', emoji: '🐨' },
  { shortcode: 'tiger', emoji: '🐯' },
  { shortcode: 'lion', emoji: '🦁' },
  { shortcode: 'cow', emoji: '🐮' },
  { shortcode: 'pig', emoji: '🐷' },
  { shortcode: 'frog', emoji: '🐸' },
  { shortcode: 'monkey', emoji: '🐵' },
  { shortcode: 'see_no_evil', emoji: '🙈' },
  { shortcode: 'hear_no_evil', emoji: '🙉' },
  { shortcode: 'speak_no_evil', emoji: '🙊' },
  { shortcode: 'unicorn', emoji: '🦄' },

  // Weather / nature
  { shortcode: 'sunny', emoji: '☀️' },
  { shortcode: 'partly_sunny', emoji: '⛅' },
  { shortcode: 'cloud', emoji: '☁️' },
  { shortcode: 'rainbow', emoji: '🌈' },
  { shortcode: 'snowflake', emoji: '❄️' },
  { shortcode: 'snowman', emoji: '⛄' },
  { shortcode: 'umbrella', emoji: '☔' },
  { shortcode: 'moon', emoji: '🌙' },
  { shortcode: 'sun', emoji: '🌞' },
  { shortcode: 'earth', emoji: '🌍' },

  // Communication
  { shortcode: 'speech_balloon', emoji: '💬' },
  { shortcode: 'thought_balloon', emoji: '💭' },
  { shortcode: 'mailbox', emoji: '📬' },
  { shortcode: 'envelope', emoji: '✉️' },
  { shortcode: 'memo', emoji: '📝' },
  { shortcode: 'page_facing_up', emoji: '📄' },
  { shortcode: 'book', emoji: '📖' },
  { shortcode: 'bookmark', emoji: '🔖' },
  { shortcode: 'chart', emoji: '📊' },
  { shortcode: 'calendar', emoji: '📅' },
]

/** Case-insensitive, substring-first then starts-with ranking. */
export function searchEmojiShortcodes(query: string, limit = 8): EmojiEntry[] {
  const q = query.toLowerCase().trim()
  if (!q) return EMOJI_SHORTCODES.slice(0, limit)
  const starts: EmojiEntry[] = []
  const contains: EmojiEntry[] = []
  for (const entry of EMOJI_SHORTCODES) {
    const code = entry.shortcode.toLowerCase()
    if (code === q) starts.unshift(entry)
    else if (code.startsWith(q)) starts.push(entry)
    else if (code.includes(q)) contains.push(entry)
  }
  return [...starts, ...contains].slice(0, limit)
}

/** Look up a single shortcode by exact match. Returns the emoji or null. */
export function findEmojiByShortcode(shortcode: string): string | null {
  const q = shortcode.toLowerCase()
  const hit = EMOJI_SHORTCODES.find(e => e.shortcode.toLowerCase() === q)
  return hit ? hit.emoji : null
}
